log_level: INFO

storage:
  storage_path: ./storage
  snapshots_path: ./snapshots

  snapshots_config:
    snapshots_storage: local

  on_disk_payload: true

service:
  host: 127.0.0.1
  http_port: 6333
  grpc_port: 6334

telemetry_disabled: true
