api_key: "APIEDFrkFz6pNKk"
api_secret: "fgT6fkifHfaLGBBT8wpUZzNaOTNZ69etiHsyblwJV1YE"

ws_url: "ws://127.0.0.1:7880"

redis:
  address: "127.0.0.1:6379"

sip_port: 5060
rtp_port: 10000-20000

use_external_ip: true

logging:
  level: debug