import os
from dotenv import load_dotenv
load_dotenv()

MONGODB_URI = os.getenv("MONGODB_URI")
DATABASE_NAME = os.getenv("DATABASE_NAME")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRE_DAYS = int(os.getenv("ACCESS_TOKEN_EXPIRE_DAYS", 60))
SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = os.getenv("SMTP_PORT")
SMTP_EMAIL = os.getenv("SMTP_EMAIL")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MODEL_NAME = os.getenv("MODEL_NAME", "gpt-5-mini")
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")
QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY", "")

SARVAM_API_KEY = os.getenv("SARVAM_API_KEY", "")
DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY", "")
VAPI_API_KEY = os.getenv("VAPI_API_KEY", "")
VAPI_SERVER_SECRET = os.getenv("VAPI_SERVER_SECRET", "")
LIVEKIT_URL = os.getenv("LIVEKIT_URL", "")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY", "")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET", "")
LIVEKIT_OUTBOUND_TRUNK_ID = os.getenv("LIVEKIT_OUTBOUND_TRUNK_ID", "")

VOBIZ_ACCOUNT_ID = os.getenv("VOBIZ_ACCOUNT_ID", "")
VOBIZ_AUTH_TOKEN = os.getenv("VOBIZ_AUTH_TOKEN", "")
VOBIZ_WEBHOOK_SECRET = os.getenv("VOBIZ_WEBHOOK_SECRET", "")
VOBIZ_TRUNK_ID = os.getenv("VOBIZ_TRUNK_ID", "")
VOBIZ_PHONE_NUMBER = os.getenv("VOBIZ_PHONE_NUMBER", "")
VOBIZ_CALLBACK_SIGNING_SECRET = os.getenv("VOBIZ_CALLBACK_SIGNING_SECRET", "")
VOBIZ_SIP_ADDRESS = os.getenv("VOBIZ_SIP_ADDRESS", "")
VOBIZ_SIP_USERNAME = os.getenv("VOBIZ_SIP_USERNAME", "")
VOBIZ_SIP_PASSWORD = os.getenv("VOBIZ_SIP_PASSWORD", "")

 
 
 





class Settings:
    MONGODB_URI: str = MONGODB_URI
    DATABASE_NAME: str = DATABASE_NAME
    JWT_SECRET_KEY: str = JWT_SECRET_KEY
    JWT_ALGORITHM: str = JWT_ALGORITHM
    ACCESS_TOKEN_EXPIRE_DAYS: int = ACCESS_TOKEN_EXPIRE_DAYS
    SMTP_HOST: str = SMTP_HOST
    SMTP_PORT: str = SMTP_PORT
    SMTP_EMAIL: str = SMTP_EMAIL
    SMTP_PASSWORD: str = SMTP_PASSWORD
    OPENAI_API_KEY: str = OPENAI_API_KEY
    REDIS_URL: str = REDIS_URL
    QDRANT_URL: str = QDRANT_URL
    QDRANT_API_KEY: str = QDRANT_API_KEY
    SARVAM_API_KEY: str = SARVAM_API_KEY
    DEEPGRAM_API_KEY: str = DEEPGRAM_API_KEY
    VAPI_API_KEY: str = VAPI_API_KEY
    VAPI_SERVER_SECRET: str = VAPI_SERVER_SECRET
    LIVEKIT_URL: str = LIVEKIT_URL
    LIVEKIT_API_KEY: str = LIVEKIT_API_KEY
    LIVEKIT_API_SECRET: str = LIVEKIT_API_SECRET
    LIVEKIT_OUTBOUND_TRUNK_ID: str = LIVEKIT_OUTBOUND_TRUNK_ID  # fixed
    VOBIZ_ACCOUNT_ID: str = VOBIZ_ACCOUNT_ID
    VOBIZ_AUTH_TOKEN: str = VOBIZ_AUTH_TOKEN
    VOBIZ_WEBHOOK_SECRET: str = VOBIZ_WEBHOOK_SECRET
    VOBIZ_TRUNK_ID: str = VOBIZ_TRUNK_ID
    VOBIZ_PHONE_NUMBER: str = VOBIZ_PHONE_NUMBER
    VOBIZ_CALLBACK_SIGNING_SECRET: str = VOBIZ_CALLBACK_SIGNING_SECRET
    VOBIZ_SIP_ADDRESS: str = VOBIZ_SIP_ADDRESS
    VOBIZ_SIP_USERNAME: str = VOBIZ_SIP_USERNAME
    VOBIZ_SIP_PASSWORD: str = VOBIZ_SIP_PASSWORD


settings = Settings()